# Numpy
Numpy is the core library for scientific computing in Python (see the full [documentation](https://numpy.org/devdocs/user/quickstart.html) which is available online). It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this tutorial useful to get started with Numpy.

In [0]:
import numpy as np


A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [0]:
a = np.array([2,3,4])             #create numpy array with initial values
a

array([2, 3, 4])

In [0]:
 a = np.arange(15)                  #range from 0 to 15-1
 a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [0]:
a=np.arange( 0, 2, 0.3 )    #start   end     step
a

In [0]:
a=np.linspace( 0, 2, 9 )             # start         end         number of elements that we want
a

In [0]:
a=np.zeros( (3,4) )                  #array of zeros
a

In [0]:
np.ones( (2,2), dtype=np.int16 )      #array of  ones

In [0]:
a=np.array([1,2,3])
np.ones_like(a)

In [0]:
a = np.arange(15)
a

In [0]:
a = np.random.random((2,3,4))              #random numbers between 0-1
a

array([[[0.54855257, 0.27745232, 0.40537946, 0.81429084],
        [0.09923258, 0.49585462, 0.46423273, 0.11314189],
        [0.63850828, 0.28092821, 0.1604648 , 0.56649355]],

       [[0.31451731, 0.48542248, 0.67135037, 0.88949259],
        [0.01997446, 0.82961227, 0.41445594, 0.02033518],
        [0.28950623, 0.753848  , 0.26132164, 0.94378479]]])

In [0]:
a=np.full((3,2), 4) # Create a constant array
a

array([[4, 4],
       [4, 4],
       [4, 4]])

In [0]:
a = np.eye(4)        # Create a 4x4 identity matrix
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [0]:
a = np.array([0, 1, 2])                      #np.tile(a, reps) create an array by repeating a the number of times given by reps 
np.tile(a, 3)

array([0, 1, 2, 0, 1, 2, 0, 1, 2])

In [0]:
a = np.array([0, 1, 2,3])
np.tile(a, (2, 2))

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [0]:
a = np.random.random((2,3,4)) 
print(a.shape)
a.reshape(6,4)               #a still the same
print(a.shape)
a=a.reshape(6,4)               #a.reshape() return a new array
print(a.shape)


(2, 3, 4)
(2, 3, 4)
(6, 4)


In [0]:
print('the number of axes (dimensions) of the array. =',a.ndim)
print('the dimensions of the array =',a.shape)
print('the total number of elements of the array =',a.size)
print('a.ndim =',a.ndim)

the number of axes (dimensions) of the array. = 1
the dimensions of the array = (4,)
the total number of elements of the array = 4
a.ndim = 1


### Basic OPerations

In [0]:
A = np.array( [[1,1],
           [0,1]] )
B = np.array( [[2,0],
            [3,4]] )

In [0]:
# Arithmetic operators on arrays apply elementwise
print( 'A+B= \n', A+B )
print( '2*A= \n',2*A)

A+B= 
 [[3 1]
 [3 5]]
2*A= 
 [[2 2]
 [0 2]]


In [0]:
# Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. 
# The matrix product can be performed using the @ operator (in python >=3.5) or the dot function or method:
 
A * B                       # elementwise product

array([[2, 0],
       [0, 4]])

In [0]:
A @ B                       # matrix product


array([[5, 4],
       [3, 4]])

In [0]:
A.dot(B)                    # another matrix product


array([[5, 4],
       [3, 4]])

In [0]:
#Also
np.dot(A, B)

In [0]:
a=np.arange(12).reshape(3,4)
a

In [0]:
print('sum =',a.sum())
print('min ',a.min())
print('max =',a.max())
print( 'sum on rows  ',a.sum(axis=0) )

##Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [0]:
import time
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
t1=time.time()
for i in range(4):
    y[i, :] = x[i, :] + v
t2=time.time()

print('time=',t2-t1)
print(y)

time= 0.00013828277587890625
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [0]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
t1=time.time()
y = x + v  # Add v to each row of x using broadcasting
t2=time.time()

print("time=",t2-t1)
print(y)

8.249282836914062e-05
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


The line y = x + v works even though x has shape (4, 3) and v has shape (3,) due to broadcasting; this line works as if v actually had shape (4, 3), where each row was a copy of v, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:



1.   If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2.   The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

3.   The arrays can be broadcast together if they are compatible in all dimensions.
4.   After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.


5.   In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.


Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the documentation.

Here are some applications of broadcasting:

In [0]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
print(x)
print(v)
print(x + v)

[[1 2 3]
 [4 5 6]]
[1 2 3]
[[2 4 6]
 [5 7 9]]


In [0]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
print(x.T)
print(w)
print((x.T + w).T)

[[1 4]
 [2 5]
 [3 6]]
[4 5]
[[ 5  6  7]
 [ 9 10 11]]


In [0]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x)
print(np.reshape(w, (2, 1)))
print(x + np.reshape(w, (2, 1)))

[[1 2 3]
 [4 5 6]]
[[4]
 [5]]
[[ 5  6  7]
 [ 9 10 11]]


In [0]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

## Universal Functions
NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.

In [0]:
print(np.exp(a))         #elementwise  exp
print(np.sin(a))         #elementwise  sin

[[2.27857122 1.12250721 2.27720713 2.424109  ]
 [1.21578745 1.08421137 1.68234875 1.71056493]
 [2.18388777 1.1523528  2.31267462 1.31599949]
 [2.0416866  2.26608405 1.60732409 1.31530032]
 [2.61320836 1.02510185 1.51968886 2.27183883]
 [1.41825409 1.53830956 1.56448216 1.65971949]]
[[0.73356214 0.1153077  0.73315503 0.77420877]
 [0.19415107 0.08076481 0.49704578 0.51140905]
 [0.70406573 0.14133099 0.74357737 0.27115852]
 [0.65469287 0.72981633 0.45695667 0.27064697]
 [0.81952334 0.02478944 0.40639549 0.73154791]
 [0.34235912 0.41749255 0.43276254 0.4852496 ]]


In [0]:
a = np.array([[10, 11, 12],
              [13, 14, 15]])

print(np.argmax(a))
print(np.argmax(a, axis=0))
print(np.argmax(a, axis=1))

## Indexing, Slicing and Iterating

In [0]:
a = np.arange(10)**3
print('a= ',a)
print('a[2:5] =',a[2:5])
print('a[0:8:2] =',a[0:8:2])
print('a[:8:2]  =',a[:8:2])
print(a[ : :-1] )            # reversed a

a=  [  0   1   8  27  64 125 216 343 512 729]
a[2:5] = [ 8 27 64]
a[0:8:2] = [  0   8  64 216]
a[:8:2]  = [  0   8  64 216]
[729 512 343 216 125  64  27   8   1   0]


In [0]:
for i in a:
  print(i)

0
1
8
27
64
125
216
343
512
729


In [0]:
b=np.array([[ 0,  1,  2,  3],
            [10, 11, 12, 13],
            [20, 21, 22, 23],
            [30, 31, 32, 33],
            [40, 41, 42, 43]])
print('b[2,3] =',b[2,3])
print('b[2:5, 1] =',b[2:5, 1])         #  rows 2,3 and 4 in the second column of b
print('b[ : ,1] =', b[ : ,1])          #all rows x col 1
print('b[-1] =', b[-1])                # the last row. Equivalent to b[-1,:]
print('b[-1,-1] =', b[-1,-1])            #last row and last col

b[2,3] = 23
b[2:5, 1] = [21 31 41]
b[ : ,1] = [ 1 11 21 31 41]
b[-1] = [40 41 42 43]
b[-1,-1] = 43


In [0]:
# The dots (...) represent as many colons as needed to produce a complete indexing tuple.
# For example, if x is an array with 5 axes, then

#     x[1,2,...] is equivalent to x[1,2,:,:,:],
#     x[...,3] to x[:,:,:,:,3] 
#     x[4,...,5,:] to x[4,:,:,5,:].
c = np.array( [[ [ 0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
                 [[100,101,102],
                 [110,112,113]]])
c[1,...]                                   # same as c[1,:,:] or c[1]


## Shape Manipulation

In [0]:
a=np.array([[ 2.,  8.,  0.,  6.],
            [ 4.,  5.,  1.,  1.],
            [ 8.,  9.,  3.,  6.]])
# The shape of an array can be changed with various commands. 
# Note that the following three commands all return a modified array, but do not change the original array:
a.shape


In [0]:
a.ravel()  # returns the array, flattened
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [0]:
a.reshape(6,2)  # returns the array with a modified shape

In [0]:
# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
a.reshape(2,-1)
print(a)
a=a.reshape(2,-1)
print(a)

[  0   1   8  27  64 125 216 343 512 729]
[[  0   1   8  27  64]
 [125 216 343 512 729]]


In [0]:
#The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array itself:
print(a)
a.resize((2,6))                   #equivalent to a=a.reshape((2,6))
print(a)

In [0]:
a.T  # returns the array, transposed

### Stacking together different arrays¶

In [0]:
a=np.array([[ 0.,  0.],
            [ 0.,  0.],
            [ 0.,  0.]])
b=np.array([[ 1.,  1.],
            [ 1.,  1.],
           [ 1.,  1.]])
            
np.vstack((a,b))

In [0]:
np.hstack((a,b))

The function column_stack stacks 1D arrays as columns into a 2D array. It is equivalent to hstack only for 2D arrays:

In [0]:
np.column_stack((a,b))     # with 2D arrays    => the same as hstack



In [0]:
a = np.array([4.,2.])
b = np.array([3.,8.])
print('column_stack \n',np.column_stack((a,b)) )    # returns a 2D array

print( 'hstack \n',np.hstack((a,b)))        # the result is different
print('vstack \n',np.vstack((a,b)) )

column_stack 
 [[4. 3.]
 [2. 8.]]
hstack 
 [4. 2. 3. 8.]
vstack 
 [[4. 2.]
 [3. 8.]]


### Copies and Views
When operating and manipulating arrays, their data is sometimes copied into a new array and sometimes not. 
There are three cases:




**1.**   ***No Copy at All***
Simple assignments make no copy of array objects or of their data.

In [0]:
a = np.arange(12)
b = a            # no new object is created
b is a           # a and b are two names for the same ndarray object


True

In [0]:
b.shape = 3,4    # changes the shape of a
a.shape


(3, 4)

In [0]:
print(id(a))
print(id(b))

139898042797152
139898042797152



***2.   View or Shallow Copy:***
Different array objects can share the same data. The view method creates a new array object that looks at the same data.



In [0]:
a = np.arange(12)
c = a.view()
print(c is a)
print(c.base is a   )                     # c is a view of the data owned by 

False
True


In [0]:
c.shape = 2,6                      # a's shape doesn't change
a.shape

(12,)

In [0]:
c[0,4] = 1234                      # a's data changes
print('c \n',c)
print('a \n',a)


c 
 [[   0    1    2    3 1234    5]
 [   6    7    8    9   10   11]]
a 
 [   0    1    2    3 1234    5    6    7    8    9   10   11]


Hint:
Slicing an array returns a view of it:


In [0]:

s = a[0:3]     # spaces added for clarity; could also be written "s = a[:,1:3]"
s[:] = 10           # s[:] is a view of s. Note the difference between s=10 and s[:]=10
a


array([  10,   10,   10,    3, 1234,    5,    6,    7,    8,    9,   10,
         11])



***3.   Deep Copy:***

The copy method makes a complete copy of the array and its data.



In [0]:
a = np.arange(12)
a.shape=3,4

In [0]:
d = a.copy()                          # a new array object with new data is created
print(d is a)
print(d.base is a )                   # d doesn't share anything with a

In [0]:
d[0,0] = 9999
a

NameError: ignored